import = ["~/.config/alacritty/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 13

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -s main-alacritty"]

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 0.97
padding = { x = 2, y = 2 }
