import = ["~/.config/alacritty/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[colors]
transparent_background_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 14

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux"]

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.97
padding = { x = 2, y = 2 }
