[colors]
transparent_background_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
blur = true
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95
option_as_alt = "OnlyLeft"
padding = { x = 1, y = 1 }
startup_mode = "Maximized"
