[env]
TERM = "xterm-256color"

[colors]
transparent_background_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 8, y = 8 }

[general]
import = ["~/.config/alacritty/tokyo-night-storm.toml"]
