set -g default-terminal 'screen-256color'

set -sg escape-time 10

# Easy config reload
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Mouse behavior
set -g mouse on

# Vi behavior
setw -g mode-keys vi

# Status bar
set -g status-interval 2
set -g status-right '#(powerline tmux right)'

# Key bindings
bind-key : command-prompt
bind-key r refresh-client
bind-key L clear-history

bind-key + select-layout main-horizontal
bind-key = select-layout main-vertical

# vim-like keys for splits and windows
bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
