set -g default-terminal 'xterm-256color'

# Mouse behavior
set -g mouse on

# Vi behavior
setw -g mode-keys vi

# Status bar
set -g status-interval 2
set -g status-right '#(powerline tmux right)'

# Enable native Mac OS X copy/paste
set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"

# Key bindings
bind-key : command-prompt
bind-key r refresh-client
bind-key L clear-history

bind-key + select-layout main-horizontal
bind-key = select-layout main-vertical

# vim-like keys for splits and windows
bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
